name: Docker Build and Push
on:
  push:
    # branches:
    #   - main
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIDOCKER_URL }}
          username: ${{ secrets.ALIDOCKER_PASSWORD }}
          password: ${{ secrets.ALIDOCKER_USERNAME }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/headscale-admin:${{ steps.meta.outputs.REPO_VERSION }}
            ${{ env.DOCKER_NAMESPACE }}/headscale-admin:latest
          platforms: linux/amd64 #,linux/arm64,linux/arm64/v8
          # platforms: |
              # linux/amd64
              # linux/arm64
              # linux/arm64/v8

